DROP TABLE if exists users;
DROP TABLE if exists films;
DROP TABLE if exists films_genres;
DROP TABLE if exists likes;
DROP TABLE if exists friends;
DROP TABLE if exists genres;
DROP TABLE if exists mpa_ratings;


CREATE TABLE if not exists users
(
    "id"       integer generated by default as identity not null primary key,
    "email"    varchar(255) not null unique,
    "login"    varchar(255) not null unique,
    "name"     varchar(255),
    "birthday" date
);

CREATE TABLE if not exists genres
(
    "id"   integer generated by default as identity primary key,
    "name" varchar(255) not null unique
);

CREATE TABLE if not exists mpa_ratings
(
    "id"   integer generated by default as identity primary key,
    "name" varchar(255) not null unique
);

CREATE TABLE if not exists films
(
    "id"               integer generated by default as identity not null primary key,
    "name"             varchar(255) not null,
    "description"      varchar(200),
    "release_date"     date,
    "duration" integer,
    "mpa"    integer not null references mpa_ratings ("id") on DELETE cascade
);

CREATE TABLE if not exists likes
(
    "film_id" integer not null references films ("id") on delete cascade,
    "user_id" integer not null references users ("id") on delete cascade,
    PRIMARY KEY ("film_id", "user_id")
);

CREATE TABLE if not exists "films_genres"
(
    "film_id"  integer not null references films ("id") on delete cascade,
    "genre_id" integer not null references genres ("id") on delete cascade,
    PRIMARY KEY ("film_id", "genre_id")
);

CREATE TABLE if not exists friends
(
    "user_id"   integer not null references users ("id") on delete cascade,
    "friend_id" integer not null references users ("id") on delete cascade,
    unique ("user_id", "friend_id")
);
