drop table if exists films cascade;
drop table if exists users cascade;
drop table if exists mpa_ratings cascade;
drop table if exists genres cascade;
drop table if exists films_genres cascade;
drop table if exists friends cascade;
drop table if exists likes cascade;
drop table if exists directors cascade;
drop table if exists films_directors cascade;
drop table if exists reviews cascade;
drop table if exists likes_reviews cascade;

CREATE TABLE if not exists genres
(
    genre_id   integer generated by default as identity primary key,
    genre_name varchar(255) not null unique
);

CREATE TABLE if not exists mpa_ratings
(
    mpa_id   integer generated by default as identity primary key,
    mpa_name varchar(255) not null unique
);

CREATE TABLE if not exists films
(
    film_id               integer generated by default  as identity not null primary key,
    film_name             varchar(255) not null,
    description      varchar(200),
    release_date     date,
    duration integer,
    mpa_id    integer not null references mpa_ratings (mpa_id) on delete cascade,
    rate integer
);

CREATE TABLE if not exists users
(
    user_id       integer generated by default as identity not null primary key,
    email    varchar(255) not null unique,
    login    varchar(255) not null unique,
    user_name     varchar(255),
    birthday date
);

CREATE TABLE if not exists films_genres
(
    film_id  integer not null references films (film_id) on delete cascade,
    genre_id integer not null references genres (genre_id) on delete cascade,
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE if not exists friends
(
    user_id   integer not null references users (user_id) on delete cascade,
    friend_id integer not null references users (user_id) on delete cascade,
    unique (user_id, friend_id)
);

CREATE TABLE if not exists likes
(
    film_id integer not null references films (film_id) on delete cascade,
    user_id integer not null references users (user_id) on delete cascade,
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE if not exists directors
(
    director_id   integer generated by default as identity primary key,
    director_name varchar(255) not null
);

CREATE TABLE if not exists films_directors
(
    film_id  integer not null references films (film_id) on delete cascade,
    director_id integer not null references directors (director_id) on delete cascade,
    PRIMARY KEY (film_id, director_id)
);

CREATE TABLE if not exists reviews
(
    review_id   integer generated by default as identity not null primary key,
    content     varchar(1000) not null,
    is_Positive     BOOLEAN not null,
    user_id     integer not null references users (user_id),
    film_id     integer not null references films (film_id),
    useful      integer not null
);

CREATE TABLE IF NOT EXISTS likes_reviews
(
    like_id     integer generated by default as identity not null primary key,
    user_id     integer not null references users (user_id),
    review_id   integer not null references reviews (review_id) on delete cascade,
    is_Positive     BOOLEAN not null
);
